site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - label: 'Cakes'
    name: 'cakes'
    folder: 'content/cakes'
    create: true
    editor:
      preview: false
    fields: 
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "list"}
  - label: 'Pricing'
    name: 'pricing'
    files: 
      - label: 'Contents'
        name: 'contents'
        file: 'content/pricing/contents.md'
        format: 'md'
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Paragraph Content", name: "content", widget: "text"}
          - label: "Prices"
            name: "prices"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: "Product Name", name: "name", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}
  - label: 'About'
    name: 'about'
    files: 
      - label: 'Contents'
        name: 'contents'
        file: 'content/about/contents.md'
        format: 'md'
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Page Contents", name: "content", widget: "text"}
